{
  "id":9,
  "name":"productdb_languages",
  "formtabs":[
    {
      "MIGX_id":15,
      "caption":"General",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":31,
          "field":"language",
          "caption":"language",
          "pos":1
        },
        {
          "MIGX_id":32,
          "field":"lang_key",
          "caption":"lang_key",
          "pos":2
        }
      ],
      "pos":1
    }
  ],
  "contextmenus":"update||publish||unpublish",
  "actionbuttons":"addItem",
  "columnbuttons":"",
  "filters":"",
  "extended":{
    "migx_add":"Add Language",
    "disable_add_item":"",
    "add_items_directly":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"productdb_languages",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "media_source_id":"",
    "multiple_formtabs":"",
    "multiple_formtabs_label":"",
    "multiple_formtabs_field":"",
    "multiple_formtabs_optionstext":"",
    "multiple_formtabs_optionsvalue":"",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"productdb",
    "classname":"productdbLang",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "sortconfig":"",
    "gridpagesize":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "has_jointable":"yes",
    "getlistwhere":"",
    "joins":"",
    "hooksnippets":"",
    "cmpmaincaption":"",
    "cmptabcaption":"Languages",
    "cmptabdescription":"Manage Languages here",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":2,
      "dataIndex":"id",
      "header":"id"
    },
    {
      "MIGX_id":3,
      "dataIndex":"language",
      "header":"language"
    },
    {
      "MIGX_id":4,
      "dataIndex":"lang_key",
      "header":"lang_key"
    },
    {
      "MIGX_id":6,
      "header":"published",
      "dataIndex":"published",
      "width":"",
      "sortable":true,
      "show_in_grid":1,
      "customrenderer":"",
      "renderer":"this.renderCrossTick",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":"",
      "editor":""
    }
  ],
  "createdby":1,
  "createdon":"2018-02-24 11:42:20",
  "editedby":1,
  "editedon":"2018-02-24 11:47:26",
  "deleted":0,
  "deletedon":null,
  "deletedby":0,
  "published":1,
  "publishedon":null,
  "publishedby":0,
  "category":"productdb"
}