{
  "id":8,
  "name":"productdb_products",
  "formtabs":[
    {
      "MIGX_id":14,
      "caption":"Main",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":30,
          "field":"name",
          "caption":"name",
          "pos":1
        }
      ],
      "pos":1
    }
  ],
  "contextmenus":"update",
  "actionbuttons":"addItem",
  "columnbuttons":"",
  "filters":"",
  "extended":{
    "migx_add":"",
    "disable_add_item":"",
    "add_items_directly":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"productdb_products",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "media_source_id":"",
    "multiple_formtabs":"",
    "multiple_formtabs_label":"",
    "multiple_formtabs_field":"",
    "multiple_formtabs_optionstext":"",
    "multiple_formtabs_optionsvalue":"",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"productdb",
    "classname":"productdbRow",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "sortconfig":"",
    "gridpagesize":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":"0",
    "check_resid_TV":"",
    "join_alias":"",
    "has_jointable":"yes",
    "getlistwhere":"",
    "joins":[
      {
        "alias":"FlatRow"
      }
    ],
    "hooksnippets":{
      "aftersave":"productdb_aftersave_product"
    },
    "cmpmaincaption":"",
    "cmptabcaption":"Products",
    "cmptabdescription":"Manage Products here",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":2,
      "dataIndex":"id",
      "header":"id"
    },
    {
      "MIGX_id":3,
      "dataIndex":"name",
      "header":"name"
    }
  ],
  "createdby":1,
  "createdon":"2018-02-23 13:34:06",
  "editedby":1,
  "editedon":"2018-02-24 11:40:49",
  "deleted":0,
  "deletedon":null,
  "deletedby":0,
  "published":1,
  "publishedon":null,
  "publishedby":0,
  "category":""
}